### ISSUE TITLE
禁止人身批评(Argumentum ad Hominem)

### ISSUE THREAD

**Issue by FrankHB** [tieba/tieba.github.com#19]
人身批评是一种常见的扰乱讨论秩序的逻辑谬误。
有必要列入TODO列表。

**Comment by FrankHB** [comment]
这点当前没有命令禁止因此不算违规，但从一些贴的效果上来看，比人身攻击和常规不文明言行的人格贬损的影响更加恶劣（尤其是隐蔽性），因此考虑在以后吧规修正中加入并严格执行。

**Comment by FrankHB** [comment]
应特别指出保留回复警告，情节严重者直接封禁，但不适用删除，以避免降低教育效果。

**Comment by FrankHB** [comment]
此条不作为不解释事项，拟直接加入禁止事项正文。

**Comment by FrankHB** [comment]
Fixed by 929f93d.

**Comment by lolisa** [comment]
吱持帝球
