### ISSUE TITLE
缺少许可证

### ISSUE THREAD

**Issue by FrankHB** [tieba/tieba.github.com#33]
如题。需要补充 `LICENSE` 文档。

**Comment by hysw** [comment]
帝球PL?

基本上是 CC0 (public domain)
或者CC-BY-NC/BSD/GPL/MIT/Apache

**Comment by FrankHB** [comment]
@hysw 草，原来还活着吗……

现在都是文档吧，那就 CC BY-NC ？

**Comment by hysw** [comment]
目测没有问题
目测帝球还是帝球

**Comment by lhmouse** [comment]
CC BY-NC-SA
